# constant parameters

WHITE_THRESHOLD = 70
OBSTACLE_DISTANCE_CM = 20
DEGREES_180 = 180
DEGREES_90 = 90
DEGREES_360 = 360
COLOR_GREEN = 3
COLOR_RED = 5
DEFAULT_SPEED = 30
DEFAULT_SPEED_ARM = 50

# port configuration

PORT_ULTRASONIC = 'in3'
PORT_TOUCH_LEFT = 'in1'
PORT_TOUCH_RIGHT = 'in2'
PORT_COLOR = 'in4'
PORT_GYRO = 'in5'